[normal_mode]
exit = "q"
switch_to_insert_mode = "i"
switch_to_visual_mode = "v"
switch_to_action_mode = "<space>"

paste = "p"

insert_line_below = "o"
insert_line_above = "O"

# The "classic" move keys
move_up = "<key_up>"
move_down = "<key_down>"
move_left = "<key_left>"
move_right = "<key_right>"

# The "vim-like" move keys
move_up = "k"
move_down = "j"
move_left = "h"
move_right = "l"

page_up = "<page_up>"
page_down = "<page_down>"


[visual_mode]
switch_to_normal_mode = "<esc>"
yank_selection = "y"
delete_selection = "d"
paste = "p"

# The "classic" move keys
move_up_and_select = "<key_up>"
move_down_and_select = "<key_down>"
move_left_and_select = "<key_left>"
move_right_and_select = "<key_right>"

# The "vim-like" move keys
move_up_and_select = "k"
move_down_and_select = "j"
move_left_and_select = "h"
move_right_and_select = "l"


[insert_mode]
switch_to_normal_mode = "<esc>"

# The "classic" move keys
move_up = "<key_up>"
move_down = "<key_down>"
move_left = "<key_left>"
move_right = "<key_right>"

page_up = "<page_up>"
page_down = "<page_down>"

delete_forward = "<del>"
delete_backward = "<backspace>"
